// <auto-generated />
using System;
using LogisticsWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticsWebAPI.Migrations.Driver
{
    [DbContext(typeof(DriverContext))]
    partial class DriverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LogisticsWebAPI.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CargoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("CargoWeight")
                        .HasColumnType("double");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TruckId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TruckId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverID");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("ActualTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("EstimatedTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StopPoint")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegisterNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameOfCompany")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Cargo", b =>
                {
                    b.HasOne("LogisticsWebAPI.Models.Order", "Order")
                        .WithMany("Cargos")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Driver", b =>
                {
                    b.HasOne("LogisticsWebAPI.Models.Truck", "Truck")
                        .WithOne("Driver")
                        .HasForeignKey("LogisticsWebAPI.Models.Driver", "TruckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Order", b =>
                {
                    b.HasOne("LogisticsWebAPI.Models.Driver", "Driver")
                        .WithMany("Orders")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogisticsWebAPI.Models.Route", "Route")
                        .WithMany("Orders")
                        .HasForeignKey("RouteId");

                    b.HasOne("LogisticsWebAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID");

                    b.Navigation("Driver");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Driver", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Order", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Route", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.Truck", b =>
                {
                    b.Navigation("Driver");
                });

            modelBuilder.Entity("LogisticsWebAPI.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
